### ISSUE TITLE
spec generation fails with error while including init tasl

### ISSUE THREAD

**Issue by ganeshrn** [ansible-network/yang#39]
# ISSUE TYPE

- Bug Report

# ANSIBLE VERSION

```
ansible --version
2.7
ansible-galaxy list | grep ansible.network
2.7.1
```

# Network OS

- Operating System (inc version) of machine running Ansible
- Network device make/model, including version

# SUMMARY

# STEPS TO REPRODUCE

```yaml
---
- hosts: iosxr
  connection: netconf
  gather_facts: no
  tasks:
  - name: include yang role
    include_role:
      name: ansible-network.yang
      tasks_from: spec
    loop:
       - openconfig-interfaces
    loop_control:
      loop_var: yang_model_name
    vars:
      ansible_network_provider: cisco_iosxr
      yang_fetch_schema: false

```

# EXPECTED RESULTS

```
spec should be generated without failure
```
# ACTUAL RESULTS

```
$ansible-playbook playbooks/yang/fetch_and_generate_spec.yml

PLAY [iosxr] *********************************************************************************************************

TASK [include yang role] *********************************************************************************************

TASK [ansible-network.yang : initialize function] ********************************************************************
fatal: [iosxr02]: FAILED! => {"reason": "Could not find or access '/Users/gnalawad/Documents/ganeshrn/playbooks/yang/includes/init.yaml' on the Ansible Controller."}

PLAY RECAP ***********************************************************************************************************
iosxr02                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0
```
