### ISSUE TITLE
XML to JSON conversion failed for ietf-netconf-monitoring.yang schema

### ISSUE THREAD

**Issue by xijq227** [ansible-network/yang#47]
# ISSUE TYPE

- Bug Report

# ANSIBLE VERSION

```
ansible --version
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nexus/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
ansible-galaxy list | grep ansible.network
- ansible-network.yang, v2.7.1
- ansible-network.network-engine, v2.7.5
- ansible-network.juniper_junos, v2.7.2
```

# Network OS

- Operating System (inc version) of machine running Ansible
```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Network device make/model, including version
```
root@Moomins_vMX-1> show version 
Hostname: Moomins_vMX-1
Model: vmx
Junos: 18.3R1.9
```

# SUMMARY

Attempt to get all available schemas from vmx by using ansible-network.yang get action. the playbook retrieve all schemas correctly in XML format and stored in `~/.ansible/tmp/xml2json/` . the task to convert xml to json failed. json file is not generated.

# STEPS TO REPRODUCE

```yaml
---
- hosts: all
  connection: netconf
  gather_facts: no

  tasks:
  - name: netconf get-all-schemas()
    include_role:
      name: ansible-network.yang
      tasks_from: get
    vars:
      yang_get_filter: <netconf-state><schemas/></netconf-state>
      ansible_network_provider: ansible-network.juniper_junos
      yang_netconf_enable_task_run: false
      yang_modules_file_path: "{{playbook_dir}}/.ansible/yang/fetch/*.yang"
      yang_search_path: "{{playbook_dir}}/.ansible/yang/fetch"
      yang_keep_tmp_files: true
      yang_get_output: ""
```

# EXPECTED RESULTS

successfully generation of json file that is converted from XML file.

# ACTUAL RESULTS

```
ansible-playbook -i moomins.yaml main.yaml 

PLAY [all] *****************************************************************************************

TASK [netconf get-all-schemas()] *******************************************************************

TASK [ansible-network.yang : initialize function] **************************************************
included: /etc/ansible/roles/ansible-network.yang/includes/init.yml for Moomins_vMX1

TASK [ansible-network.yang : read ansible_min_version from meta data] ******************************
ok: [Moomins_vMX1]

TASK [ansible-network.yang : validate minimum Ansible version] *************************************
skipping: [Moomins_vMX1]

TASK [ansible-network.yang : validate connection is netconf] ***************************************
skipping: [Moomins_vMX1]

TASK [ansible-network.yang : validate role spec] ***************************************************
ok: [Moomins_vMX1]

TASK [ansible-network.yang : enable netconf] *******************************************************
skipping: [Moomins_vMX1]

TASK [ansible-network.yang : get configuration and/or state data from Moomins_vMX1] ****************
 [WARNING]: Platform linux on host Moomins_vMX1 is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more
information.
ok: [Moomins_vMX1]

TASK [ansible-network.yang : convert xml to json encoding of data model with YANG as per rfc 7951] ***
fatal: [Moomins_vMX1]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'yang_xml2json'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Error while reading json document: [Errno 2] No such file or directory: '/home/nexus/.ansible/tmp/xml2json/f64e6cff-ab7e-4007-8193-f9416292976f.json'"}

PLAY RECAP *****************************************************************************************
Moomins_vMX1               : ok=4    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   
```
