### ISSUE TITLE
Unable to specify multiple yang files for yang_json2xml lookup plugin

### ISSUE THREAD

**Issue by markafarrell** [ansible-network/yang#9]
# ISSUE TYPE

- Feature Idea

# ANSIBLE VERSION

```
ansible --version

ansible 2.6.2
  config file = None
  configured module search path = [u'/home/markfarrell/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

ansible-galaxy list -p .
- ansible-network.yang, (unknown version)
```

# Network OS

- Operating System (inc version) of machine running Ansible
Ubuntu 18.04 x86_64

- Network device make/model, including version
N/A

# SUMMARY
You can not use the yang_json2xml lookup to generate xml for more than one yang model at a time.

# STEPS TO REPRODUCE

```yaml
- name: Generate netconf
      set_fact:
        netconf_xml: "{{ lookup('yang_json2xml', 'input.json', yang_file='yang-models/*.yang',
                      search_path='yang/') }}"
```

# EXPECTED RESULTS

netconf_xml contains valid xml for more than one yang model

# ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'yang_json2xml'. Error was a <class 'ansible.errors.AnsibleError'>, original message: yang/*.yang invalid file path"
}
```
